/* ==========================================================================
   report.js — renders index.html from data/report_metrics.json
   (generated by analysis/analysis.py). No statistic is computed or typed here:
   every number in the text is a [data-m] binding to that file.
   ========================================================================== */
(function () {
  "use strict";
  const { fmt, el, teamBadge, avatar, countUp, compact, POS_COLORS, NAVY, RED } = window.RIB;
  const C = window.Charts;

  function get(obj, path) { return path.split(".").reduce((o, k) => (o == null ? o : o[k]), obj); }

  /** Format a bound value exactly as the static HTML does (the QA script uses the same rule). */
  function formatBound(v, d, f, path) {
    if (typeof v === "number" && /season/.test(path)) return String(v); // years: no thousands separator
    if (typeof v === "number") return fmt(f === "abs" ? Math.abs(v) : v, d);
    return String(v);
  }

  function bindNumbers(M) {
    const mismatches = [];
    document.querySelectorAll("[data-m]").forEach((n) => {
      const v = get(M, n.dataset.m);
      if (v === undefined) { mismatches.push(n.dataset.m + " (missing)"); return; }
      const txt = formatBound(v, +(n.dataset.d || 0), n.dataset.f, n.dataset.m);
      if (n.textContent.trim() !== txt) mismatches.push(`${n.dataset.m}: page "${n.textContent.trim()}" vs data "${txt}"`);
      n.textContent = txt;
    });
    window.__reportBindingMismatches = mismatches;
    if (mismatches.length) console.warn("Static text differed from report_metrics.json (data wins):", mismatches);
  }

  function kpis(M) {
    const cards = document.querySelectorAll("[data-count]");
    const run = (n) => {
      const v = get(M, n.dataset.count);
      countUp(n, v, 0, { format: n.dataset.compact ? (x) => compact(x) : (x) => fmt(x, 0), duration: 1100 });
    };
    if (!("IntersectionObserver" in window)) { cards.forEach(run); return; }
    const io = new IntersectionObserver((es) => es.forEach((e) => { if (e.isIntersecting) { run(e.target); io.unobserve(e.target); } }), { threshold: 0.4 });
    cards.forEach((c) => io.observe(c));
  }

  function heroSpark(M) {
    const svg = document.getElementById("hero-spark");
    if (!svg || !window.d3) return;
    const v = M.f1.pass_ypg, W = 300, H = 70;
    const x = d3.scaleLinear().domain([0, v.length - 1]).range([6, W - 6]);
    const y = d3.scaleLinear().domain(d3.extent(v, (d) => d.value)).range([H - 8, 8]);
    const s = d3.select(svg);
    s.append("path").attr("d", d3.line().x((d, i) => x(i)).y((d) => y(d.value)).curve(d3.curveMonotoneX)(v))
      .attr("stroke", "#ff6b7d").attr("vector-effect", "non-scaling-stroke");
    [0, v.length - 1].forEach((i) => s.append("circle").attr("cx", x(i)).attr("cy", y(v[i].value)).attr("r", 3.5).attr("fill", "#ff6b7d"));
  }

  const season = (d) => ({ x: d.season, y: d.value });

  function charts(M) {
    // 1 — passing yards per team-game
    C.line("#c-f1", {
      series: [{ key: "pass", label: "Passing yds / team-game", color: NAVY, values: M.f1.pass_ypg.map(season) }],
      yFormat: (v) => fmt(v, 0), tipFormat: (v) => fmt(v, 1), endLabels: true, area: true,
      ariaLabel: "Line chart of passing yards per team-game by season",
    });
    // 2 — 300-yard games
    const hi2 = new Set([M.meta.first_season, M.meta.last_season]);
    C.columns("#c-f2", {
      data: M.f2.games.map((d) => ({ key: d.season, label: String(d.season), value: d.value, rate: d.rate })),
      highlight: new Set([M.meta.last_season]), labels: "all", seasonAxis: true,
      yFormat: (v) => fmt(v), valueName: "300-yard games",
      tipRows: (d) => [{ value: fmt(d.value), label: "300-yard passing games", color: hi2.has(d.key) && d.key === M.meta.last_season ? RED : NAVY, key: "swatch" },
        { value: fmt(d.rate, 1) + "%", label: "of team-games" }],
      ariaLabel: "Column chart of 300-yard passing games by season",
    });
    // 3 — sack rate
    C.columns("#c-f3", {
      data: M.f3.sack_rate.map((d) => ({ key: d.season, label: String(d.season), value: d.value })),
      highlight: new Set([M.f3.peak_season]), labels: "highlight", seasonAxis: true,
      yFormat: (v) => fmt(v, 0) + "%", tipFormat: (v) => fmt(v, 2) + "%", valueName: "Sack rate",
      ariaLabel: "Column chart of sack rate by season",
    });
    // 4 — giveaways
    C.line("#c-f4", {
      series: [{ key: "give", label: "Giveaways / team-game", color: NAVY, values: M.f4.give_pg.map(season) }],
      yFormat: (v) => fmt(v, 2), endLabels: true, area: true,
      tipFormat: (v) => fmt(v, 2),
      ariaLabel: "Line chart of giveaways per team-game by season",
    });
    // 5 — rushing yards per team-game
    C.line("#c-f5", {
      series: [{ key: "rush", label: "Rushing yds / team-game", color: "#1c6e47", values: M.f5.rush_ypg.map(season) }],
      yFormat: (v) => fmt(v, 0), tipFormat: (v) => fmt(v, 1), endLabels: true, area: true,
      annotations: [{ x: M.f5.peak_season, y: M.f5.peak, text: `Peak: ${fmt(M.f5.peak, 1)} (${M.f5.peak_season})`, dy: -24 }],
      ariaLabel: "Line chart of rushing yards per team-game by season",
    });
    // 6 — QB share of rushing yards
    C.line("#c-f6", {
      series: [{ key: "qb", label: "QB share of rushing yards", color: POS_COLORS.QB, values: M.f6.qb_share.map(season) }],
      yFormat: (v) => fmt(v, 0) + "%", tipFormat: (v) => fmt(v, 1) + "%", endLabels: true, area: true,
      annotations: [{ x: M.f6.peak_season, y: M.f6.peak, text: `Peak: ${fmt(M.f6.peak, 1)}%`, dy: -24 }],
      ariaLabel: "Line chart of quarterbacks' share of rushing yards by season",
    });
    // 7 — target share stacked
    const keys = ["WR", "TE", "RB", "QB"], names = { WR: "Wide receivers", TE: "Tight ends", RB: "Running backs", QB: "Quarterbacks" };
    const lg = document.getElementById("lg-f7");
    keys.slice(0, 3).forEach((k) => lg.appendChild(el("li", null, el("i", { class: "swatch", style: { background: POS_COLORS[k] } }), names[k])));
    C.stacked("#c-f7", {
      data: M.f7.share.map((d) => Object.assign({ key: d.season, label: String(d.season) }, d)),
      keys, colors: POS_COLORS, names, darkText: ["TE"],
      ariaLabel: "Stacked column chart of target share by position and season",
    });
    // 8 — home edge
    C.columns("#c-f8", {
      data: M.f8.by_season.map((d) => ({ key: d.season, label: String(d.season), value: d.diff, home: d.home, away: d.away })),
      color: NAVY, negColor: RED, labels: "all", seasonAxis: true,
      yFormat: (v) => (v > 0 ? "+" : "") + fmt(v, 0), labelFormat: (v) => (v > 0 ? "+" : "") + fmt(v, 1),
      tipRows: (d) => [{ value: (d.value > 0 ? "+" : "") + fmt(d.value, 1), label: "Home edge (yds)", color: d.value < 0 ? RED : NAVY, key: "swatch" },
        { value: fmt(d.home, 1), label: "Home yds / game" }, { value: fmt(d.away, 1), label: "Away yds / game" }],
      ariaLabel: "Column chart of home minus away offensive yards per game by season",
    });
    // 9 — teams
    const teams = M.f9.teams, last = teams.length - 1;
    C.ranked("#c-f9", {
      rows: teams.map((t, i) => ({ key: t.team, label: t.name, value: t.ypg, highlight: i === 0 || i === last,
        badge: () => teamBadge(t.team, 22) })),
      format: (v) => fmt(v, 1),
      tipTitle: (r) => r.label,
      tipRows: (r) => { const t = teams.find((x) => x.team === r.key); return [
        { value: fmt(t.ypg, 1), label: "Offensive yds / game" }, { value: fmt(t.tdpg, 2), label: "TDs scored / game" },
        { value: fmt(t.games), label: "Team-games" }, { value: (t.ypg - M.f9.league_ypg > 0 ? "+" : "") + fmt(t.ypg - M.f9.league_ypg, 1), label: "vs league average" }]; },
    });
    // 10 — fantasy distribution
    C.rangePlot("#c-f10", {
      rows: M.f10.positions.map((p) => Object.assign({ key: p.position, label: { QB: "Quarterbacks", RB: "Running backs", WR: "Wide receivers", TE: "Tight ends" }[p.position], color: POS_COLORS[p.position] }, p)),
      xLabel: "PPR fantasy points in a game", xFormat: (v) => fmt(v, 0),
      ariaLabel: "Range plot of PPR fantasy points per game by position",
    });
    // 11 — players
    const L = M.f11.leaders;
    C.ranked("#c-f11", {
      rows: L.map((p, i) => ({ key: p.player_id, label: p.name, sub: `${p.position} · ${p.teams.join(" → ")}`,
        value: p.scrimmage_yards, highlight: i === 0, badge: () => avatar(p.name, p.headshot, p.teams[p.teams.length - 1]) })),
      format: (v) => fmt(v),
      tipTitle: () => "2015–2025 regular season",
      tipHead: (r) => { const p = L.find((x) => x.player_id === r.key); return el("div", { class: "tt-head" }, avatar(p.name, p.headshot, p.teams[p.teams.length - 1]), el("div", null, el("div", { class: "tt-name", text: p.name }), el("div", { class: "tt-sub", text: `${p.position} · ${p.teams.join(", ")}` }))); },
      tipRows: (r) => { const p = L.find((x) => x.player_id === r.key); return [
        { value: fmt(p.scrimmage_yards), label: "Scrimmage yards" }, { value: fmt(p.rushing_yards), label: "Rushing" },
        { value: fmt(p.receiving_yards), label: "Receiving" }, { value: fmt(p.td_scored), label: "TDs scored" },
        { value: fmt(p.games), label: "Games with a stat" }, { value: fmt(p.per_game, 1), label: "Yards per game" }]; },
    });
    const cards = document.getElementById("leader-cards");
    [[M.f11.top, "Most scrimmage yards", fmt(M.f11.top.scrimmage_yards) + " yds", 1],
     [M.f11.best_per_game, "Best per game (top 10)", fmt(M.f11.best_per_game.per_game, 1) + " yds/g", 2]].forEach(([p, cap, val, rank]) => {
      cards.appendChild(el("div", { class: "leader-card", "data-rank": String(rank) },
        avatar(p.name, p.headshot, p.teams[p.teams.length - 1]),
        el("div", null, el("span", { text: cap }), el("b", { text: p.name }), el("strong", { text: val }))));
    });
  }

  /* ---------------------------------------------------------------- "Show the numbers" tables */
  function tableSpecs(M) {
    const s = (arr, k) => Object.fromEntries(arr.map((d) => [d.season, d[k || "value"]]));
    const seasons = M.f1.pass_ypg.map((d) => d.season);
    const bySeason = (cols) => ({ head: ["Season", ...cols.map((c) => c[0])], rows: seasons.map((y) => [String(y), ...cols.map((c) => c[1](y))]) });
    const pass = s(M.f1.pass_ypg), att = s(M.f1.att_pg), ry = s(M.f5.rush_ypg), ypc = s(M.f5.ypc), car = s(M.f5.car_pg), r1k = s(M.f5.rushers_1000);
    const qs = s(M.f6.qb_share), qy = s(M.f6.qb_yards), ir = s(M.f4.int_rate), fp = s(M.f4.fum_pg), gp = s(M.f4.give_pg), sr = s(M.f3.sack_rate);
    return {
      f1: bySeason([["Pass yds / team-game", (y) => fmt(pass[y], 1)], ["Attempts / team-game", (y) => fmt(att[y], 1)]]),
      f2: { head: ["Season", "300-yd games", "% of team-games"], rows: M.f2.games.map((d) => [String(d.season), fmt(d.value), fmt(d.rate, 1) + "%"]) },
      f3: bySeason([["Sack rate", (y) => fmt(sr[y], 2) + "%"]]),
      f4: bySeason([["Giveaways / team-game", (y) => fmt(gp[y], 2)], ["INT rate", (y) => fmt(ir[y], 2) + "%"], ["Fumbles lost / team-game", (y) => fmt(fp[y], 2)]]),
      f5: bySeason([["Rush yds / team-game", (y) => fmt(ry[y], 1)], ["Yards per carry", (y) => fmt(ypc[y], 2)], ["Carries / team-game", (y) => fmt(car[y], 1)], ["1,000-yd rushers", (y) => fmt(r1k[y])]]),
      f6: bySeason([["QB share of rush yds", (y) => fmt(qs[y], 1) + "%"], ["QB rushing yards", (y) => fmt(qy[y])]]),
      f7: { head: ["Season", "WR", "TE", "RB", "QB"], rows: M.f7.share.map((d) => [String(d.season), ...["WR", "TE", "RB", "QB"].map((k) => fmt(d[k], 1) + "%")]) },
      f8: { head: ["Season", "Home yds/g", "Away yds/g", "Home edge"], rows: M.f8.by_season.map((d) => [String(d.season), fmt(d.home, 1), fmt(d.away, 1), (d.diff > 0 ? "+" : "") + fmt(d.diff, 1)]) },
      f9: { head: ["#", "Team", "Yds / game", "TDs / game", "Games"], rows: M.f9.teams.map((t, i) => [String(i + 1), t.name, fmt(t.ypg, 1), fmt(t.tdpg, 2), fmt(t.games)]) },
      f10: { head: ["Position", "Games", "Mean", "Median", "P10", "P25", "P75", "P90", "20+ pts"], rows: M.f10.positions.map((p) => [p.position, fmt(p.n), fmt(p.mean, 2), fmt(p.median, 1), fmt(p.p10, 1), fmt(p.p25, 1), fmt(p.p75, 1), fmt(p.p90, 1), fmt(p.share20, 1) + "%"]) },
      f11: { head: ["#", "Player", "Pos", "Scrimmage", "Rush", "Rec", "Games", "Per game"], rows: M.f11.leaders.map((p, i) => [String(i + 1), p.name, p.position, fmt(p.scrimmage_yards), fmt(p.rushing_yards), fmt(p.receiving_yards), fmt(p.games), fmt(p.per_game, 1)]) },
    };
  }
  function tables(M) {
    const specs = tableSpecs(M);
    document.querySelectorAll("details.numbers").forEach((d) => {
      const spec = specs[d.dataset.table];
      if (!spec) return;
      const t = el("table", { class: "num-table" },
        el("thead", null, el("tr", null, spec.head.map((h) => el("th", { scope: "col", text: h })))),
        el("tbody", null, spec.rows.map((r) => el("tr", null, r.map((c, i) => el(i === 0 ? "th" : "td", i === 0 ? { scope: "row", text: c, style: { textAlign: "left", fontWeight: 600, color: "#0d1726", textTransform: "none", letterSpacing: 0, fontSize: "13px" } } : { text: c }))))));
      d.appendChild(el("div", { class: "num-table-wrap" }, t));
    });
  }

  async function init() {
    let M;
    try { M = await window.RIB.loadJSON("data/report_metrics.json"); }
    catch (err) {
      document.querySelectorAll(".chart, .ranked").forEach((c) => window.RIB.showLoadError(c, err));
      return;
    }
    window.__reportMetrics = M;
    bindNumbers(M);
    kpis(M);
    heroSpark(M);
    charts(M);
    tables(M);
    document.documentElement.dataset.ready = "1";
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
